### ISSUE TITLE
Can't copy DPS on chat.

### ISSUE THREAD

**Issue by Priscatella** [lunyx/CasualMeter#100]
I have tried everything.
Control+Insert is not working.

This is my keyboard: https://images-na.ssl-images-amazon.com/images/I/71sgesqSvnL._SL1500_.jpg

As you can see there are two inserts keys. One right under the audio keys and one where the 0 in the numpad is located.

Yes, I open up my chat so it's ready to write and it still doesn't work.

I went to the setting folder "settings.json" and did my best to modify correctly the coding.

    "ModifierPaste": "Control",
    "ModifierReset": "Control",
    "ModifierSave": "Control",
    "Paste": "Insert",
    "Reset": "Delete",
    "Save": "End"

I have changed countless times the modifier key into Shift and Alt.
The Paste key I have changed it to: Home, End, P, 0 (Zero).

In one of the combinations I was doing I set it up like this:

    "ModifierPaste": "Shift",
    "ModifierReset": "Control",
    "ModifierSave": "Control",
    "Paste": "Insert",
    "Reset": "Delete",
    "Save": "End"

And now no matter what I do it won't let me change it.

If I select properties and only-read option, it doesn't let me launch the meter but if I don't have that selected it keeps resetting into Shift+Insert, which it would be fine if it worked, but it doesn't.

Help please?

**Comment by Priscatella** [comment]
I forgot to add I'm running both Tera and CasualMeter as admin.

And seems that the file can't save the new data added if the meter is running. Haven't confirmed this but I did read it in old posts.
Still, pasting the dps isn't working.

**Comment by Gl0** [comment]
Meter overwrites its config with actual values on exit, so you should change it only when meter is off.
Setting file as readonly may cause meter error or it may ignore all settings and use default values.

**Comment by lunyx** [comment]
Readonly will cause errors when it tries to save settings.  I'm not sure if there's some strange mapping on the key code for the insert key on your keyboard.  Closing the meter will overwrite settings with what's actually detected.  Seeing how this is a common issue, I'm thinking about adding in change detection when the file changes.  In any case, for now, don't modify the setting file before closing the meter first.

**Comment by Priscatella** [comment]
Ty for your quick replies.

I have proceed to uninstall the whole meter and reinstall it again. 
Will let you know how it will work.

Before uninstalling I managed to make the ctrl+Insert work and it copied "00:00 :"
That's it. But that was only when the dpsmeter was empty. When it had some damage registered it wouldn't copy anything.

I don't know whats happening with my meter :x

**Comment by lunyx** [comment]
Try deleting the settings file and launching the meter again.  This will clear any customizations you have and make sure you're starting froma  fresh file.

**Comment by Priscatella** [comment]
Yush.
Instead of deleting the setting files I just deleted EVERYTHING.
Seems I had downloaded this zip (which I did extract) before installing Casual Meter, the zip is called CasualMeter-Master.
I also made sure to delete that.

I installed everything again and first thing I did was changing the inactivity timer and both the modifier to Shift and the Paste to End.

Relaunched everything and... IT WORKED!!!!

I'm so happy right now. Thanks for your support guys ^^

Another question, a little bit offtopic. Is it possible to edit the:

  "DpsPasteFormat": "{Boss} {Time} : @{Name} {DPS} {DamagePercent}",
To add {HealStat} at the end?

I don't know the command of the total healing done that appears in the meter and I would like it displayed.

**Comment by Gl0** [comment]
There is no support of pasting heal stats here, but you can look at [fork](https://github.com/albmar/CasualMeter/tree/mod_output), where a lot of additional stats are available to paste.

**Comment by Priscatella** [comment]
Tyvm. Very useful link ^^
