### ISSUE TITLE
Won't export dps to Teradps.io

### ISSUE THREAD

**Issue by Priscatella** [lunyx/CasualMeter#103]
When I used ShinraMeter I had to copy a key and username into a file.

I don't know how to make it work with CasualMeter and I don't want to use ShinraMeter again, so yeah, help please, I'm a little newbie.

**Comment by lunyx** [comment]
You do the same thing with CasualMeter.  Open the meter, right-click the tray icon to choose to open the settings directory.  Then, close the meter, open the settings.json file, and paste in the keys into the appropriate fields.

**Comment by Priscatella** [comment]
Oooooo I see, thank you. I must have been blind.
That was a quick answer by the way ^^
