### ISSUE TITLE
Not full dps recording 

### ISSUE THREAD

**Issue by TheRaven06** [lunyx/CasualMeter#104]
I was playing today with CM to actually see my dmg. Class -> Ninja, issue spotted -> not full dps is recording. As i could saw in chat combat tab I did few M crits with Fire Avalanche skill but CM didnt record them. Highest crit with CM was 1.1M, when i actually did over 7M. It's like there was too many dmg done in too short time.

**Comment by Gl0** [comment]
May be you have "ignore oneshots" option active and hit the mob with less then 700k HP?

**Comment by TheRaven06** [comment]
It was daily bams run and i didnt oneshoot him

**Comment by lunyx** [comment]
Closed unless you have some screenshots/video demonstrating the issue.

**Comment by TheRaven06** [comment]
Didnt do them but i see u dont even wanna look on that, so ill just try another meter. Good luck

**Comment by Gl0** [comment]
We can't reproduce it. The core of all currently working meters is the same, and it shows even higher crits of FA successfully.
