### ISSUE TITLE
Flagged as Virus?

### ISSUE THREAD

**Issue by dayshinetl** [lunyx/CasualMeter#105]
I was trying to download the Casual Meter but my computer flagged it as a Virus and prevented me from downloading. Is it safe to use?

**Comment by dayshinetl** [comment]
https://www.microsoft.com/security/portal/threat/encyclopedia/entry.aspx?name=Trojan%3aWin32%2fSpallowz.A!cl&threatid=2147697481&enterprise=0

**Comment by lunyx** [comment]
Is that what it actually get flagged as?  Windows Defender doesn't detect anything for me.

**Comment by Gl0** [comment]
It's proactive defense on win 10, seems triggered by silent install.

**Comment by lunyx** [comment]
Strange then because I'm on W10 as well.  I know Chrome flagged it before due to silent installer, but that was already resolved.  Seems like there's something else that's causing issues as well.

**Comment by Gl0** [comment]
There was a number of reports that MS blocks your installer on start attempt (not on download)
