### ISSUE TITLE
Exporting to Excel stopped working

### ISSUE THREAD

**Issue by ArcWyrm** [lunyx/CasualMeter#106]
Autoexport to excel was working until 4 days ago, any ideas on what i can do? I have tried:
-disabling and re-enabling autoexporting to Excel
-Pressing Control-Page Down, didn't show me the view on excel, but triggered the save function.
-After a clean reinstall deleting the Documents>CasualMeter, %UserProfile%\AppData\Local\CasualMeter and the %UserProfile%\AppData\Roaming\CasualMeter, I was able to Control-Page Down to view the current meter in Excel, but it did not export to the export directory. I killed a basilisk in Island of Dawn, if it is important.

Thanks in advance

**Comment by Gl0** [comment]
May be you turned on alternate boss detection mode, so that meter does not treat BAMs as bosses? (changing mode does not affect already seen mobs in current session - need to relog to clear list of seen mobs).

**Comment by ArcWyrm** [comment]
I also did channelworks before I reinstalled, with no result. I only killed the BAMs after doing a clean install, so I am not sure if the alternate boss detection mode is on by default, and I have not yet run a dungeon after reinstalling. I will try it out tomorrow, thanks for the suggestion

**Comment by lunyx** [comment]
Ctrl + PgDn only does an export to temporary.  You should still have auto-export on if you want to view in your exports directory.  Also, both only work on bosses.

**Comment by ArcWyrm** [comment]
Yep, I just ran Channelworks and it didn't export. I only included the Ctrl+PgDn as proof that exporting to excel still works.

**Comment by ArcWyrm** [comment]
After the recent update, autoexporting to excel still wasn't working for me. However, after uninstalling CasualMeter and WinPcap(i know it wouldn't make a difference, i did it anyway) and reinstalling them, and disabling uploads to teradps.io, it worked for me. Thanks

**Comment by lunyx** [comment]
You're actually right.  This seems to be a bug with enabling both. Looking into fixing this.

**Comment by lunyx** [comment]
Fixed now.
