### ISSUE TITLE
i have a problem with using wtfast, help please?

### ISSUE THREAD

**Issue by hollaterin** [lunyx/CasualMeter#107]
i dont understand your guide =/

**Comment by Gl0** [comment]
1.Switch to raw sockets mode (require firewall exception and running meter as admin).
2.Check that it working in that mode without wtfast.
3.Add line `127.0.0.1 NA wtfast` to servers-override.txt
4.Start meter and connect game via wtfast, it should be working.

**Comment by hollaterin** [comment]
doesnt work :(

**Comment by Gl0** [comment]
At which step?
I forgot to mention the change "NA" to your region code.

**Comment by hollaterin** [comment]
currently on the server-overrides.txt i have
"# 127.0.0.1 NA wtfast"

**Comment by hollaterin** [comment]
i deleted the rest, i didnt know i needed it

**Comment by Gl0** [comment]
# = comment, this line is ignored. delete this symbol
