### ISSUE TITLE
teradpsio

### ISSUE THREAD

**Issue by jobsidi** [lunyx/CasualMeter#109]
Please add an ability to set custom dps meter server adress to settings.json
At this moments its hard coded
https://github.com/lunyx/CasualMeter/blob/master/CasualMeter.Common/TeraDpsApi/DataExporter.cs#L209
No json result package formatting is required. For example, 
http://teradps.io/api/que -> http://myserver.com/api/que
I want to create own free dps site for limited tera servers countries (i havn't so strong server for all of them) because teradps.io is commercial now.  Thx/

**Comment by lunyx** [comment]
I'm actually starting work on my own implementation as well.  What are your current plans and how far along are you?

**Comment by jobsidi** [comment]
I see teradps.io is down atm.
My code base is about 80% finished. I need to add autorization, captcha, e-mail activation, user key generation and a little bit more examples with specific parameters like event -80% skills cd, i dont think that it's necessary to exclude that results like it was on teradps.io, just need to add a special mark.
When i finish this work i will request for the official support of ddestiny development. Its the company of russian section tera online.
