### ISSUE TITLE
cant connect to the server

### ISSUE THREAD

**Issue by aubreezy** [lunyx/CasualMeter#110]
I have reinstalled casual meter and winpcap. But its still not connecting to the server

**Comment by Gl0** [comment]
If you are playing on EU - wait for @lunyx to return and publish update, or use [my beta](https://github.com/Gl0/CasualMeter/releases), or download [fresh database](https://github.com/neowutran/TeraDpsMeterData/archive/master.zip), extract it to ./res subfolder in meter directory, overwriting all files, and rename ./res/opcodes/302664.txt to ./res/opcodes/opcodes-EU.txt.

**Comment by aubreezy** [comment]
I'm not playing on EU

**Comment by Gl0** [comment]
Try to use raw sockets mode (need firewall exception for all incoming traffic and running meter as admin)

**Comment by aubreezy** [comment]
I did what you said and it did not work
