### ISSUE TITLE
Error with DLL? 

### ISSUE THREAD

**Issue by MajorArmagedon** [lunyx/CasualMeter#111]
System.DllNotFoundException: Unable to load DLL 'wpcap': Could not find the specified module. (Exception from HRESULT: 0x8007007e)

Someone can help me?

**Comment by Gl0** [comment]
Either install winpcap/npcap/etc or switch to raw sockets mode.

**Comment by MajorArmagedon** [comment]
I fix that problem yourshelf, but thanks :D
