### ISSUE TITLE
lunyx.net is down

### ISSUE THREAD

**Issue by Gl0** [lunyx/CasualMeter#112]
subj

**Comment by lunyx** [comment]
Looking into it.

**Comment by lunyx** [comment]
Is it causing issues with meter start?  I actually haven't tested this scenario before.

**Comment by Gl0** [comment]
Yes, user reported that meter was not showing while checking for updates (not sure whether it will end doing it by timeout or not).

**Comment by lunyx** [comment]
Seems like it'll open when it times out.  Just tested it.  Not sure what's going on with the server, but it might take a day, and in the worst case, I will have to find a new host.

**Comment by lunyx** [comment]
It's up now.
