### ISSUE TITLE
New update and Ninja crit percent

### ISSUE THREAD

**Issue by lamjohn63** [lunyx/CasualMeter#113]
With the new update when I try using the casual meter it counts "Focus" as a move and makes it that it adds extra hits to the count and because it does not crit the overall crit percent goes down. I found it only counts for you if you play ninja and other ninja's in the party are not affected. Here is a flat view of two ninja (one being me), as you can see (do not know if this is why it is affecting it) on one Focus is being counted and on the other it isn't.
![focus](https://cloud.githubusercontent.com/assets/21191555/17883763/d4a12908-6957-11e6-8053-945d59496694.png)

**Comment by Gl0** [comment]
Mana over time (as well as DOT and HOT) can be counted only by meter of affected player or player that applied it. That's why you see it only in your meter stats.
