### ISSUE TITLE
Cannot connect to the EU server

### ISSUE THREAD

**Issue by dancemacabra** [lunyx/CasualMeter#116]
Where should I save dps meter? Can it be there? http://prnt.sc/clrmrw
I've used @Gl0 hints and instructions and I still see this http://prnt.sc/clrnsf 
These are my settings http://prnt.sc/clrnyd
Can someone help me with this issue and explain step by step? I don't know if I overwritted and changed all files correctly
Why dps meter doesn't work on EU servers as well as on NA servers?
Thanks

**Comment by Gl0** [comment]
If you are using raw sockets - you should add firewall rule, allowing all incoming traffic for meter .exe (make sure, that there are no macro in the path like %localappdata%). + You should run meter as admin.

**Comment by dancemacabra** [comment]
Thank you very much!, but i use ShinraMeter xDDDD, but really very thank you, bless!
