### ISSUE TITLE
No dmg shown

### ISSUE THREAD

**Issue by Phobie53** [lunyx/CasualMeter#118]
Hello,

First time I'm using a DPS Meter, I'm on EU server and I never get any dmg in Casual Meter : 
![image](https://cloud.githubusercontent.com/assets/6780510/19618581/1c4193c6-984f-11e6-98fe-d7f630d5cb0b.png)

This is my config:
![image](https://cloud.githubusercontent.com/assets/6780510/19618587/2affec0a-984f-11e6-82d7-6087ab859a51.png)

Oh just saw the log file : 

> 2016-10-21 23:57:39,787 [1] INFO  CasualMeter.App - Checking for updates.
2016-10-21 23:57:40,189 [1] INFO  CasualMeter.App - Current Version: v1.2.1.14
2016-10-21 23:57:40,800 [1] INFO  CasualMeter.App - Starting up.
2016-10-21 23:57:41,303 [14] INFO  CasualMeter.Common.UI.ViewModels.CasualViewModelBase - Sniffer has been enabled.
2016-10-21 23:58:53,311 [12] INFO  CasualMeter.Common.UI.ViewModels.CasualViewModelBase - Sniffer has been disabled.
2016-10-21 23:58:53,357 [12] INFO  CasualMeter.Common.UI.ViewModels.CasualViewModelBase - Sniffer has been enabled.
2016-10-21 23:58:54,680 [13] INFO  CasualMeter.Common.UI.ViewModels.CasualViewModelBase - Sniffer has been disabled.
2016-10-21 23:58:54,763 [13] INFO  CasualMeter.Common.UI.ViewModels.CasualViewModelBase - Sniffer has been enabled.
2016-10-22 00:08:56,102 [1] INFO  CasualMeter.App - Closing.
2016-10-22 00:24:02,238 [1] INFO  CasualMeter.App - Checking for updates.
2016-10-22 00:24:02,735 [1] INFO  CasualMeter.App - Current Version: v1.2.1.14
2016-10-22 00:24:03,166 [1] INFO  CasualMeter.App - Starting up.
2016-10-22 00:24:03,428 [14] INFO  CasualMeter.Common.UI.ViewModels.CasualViewModelBase - Sniffer has been enabled.
2016-10-22 00:25:47,566 [15] INFO  CasualMeter.Common.UI.ViewModels.CasualViewModelBase - Connected to server Killian.
2016-10-22 00:25:48,598 [15] ERROR CasualMeter.App - System.IO.FileNotFoundException: Le fichier 'C:\Users\Enzo\AppData\Local\CasualMeter\app-1.2.1.14\res\opcodes\306697.txt' est introuvable.
Nom de fichier : 'C:\Users\Enzo\AppData\Local\CasualMeter\app-1.2.1.14\res\opcodes\306697.txt'
   à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   à System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   à System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   à System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   à System.IO.StreamReader..ctor(String path, Encoding encoding)
   à System.IO.File.ReadLines(String path)
   à Tera.Game.OpCodeNamer.ReadOpCodeFile(String filename) dans D:\Workspace\visualstudio\CasualMeter\Tera.Core\Game\Services\OpCodeNamer.cs:ligne 37
   à Tera.Game.OpCodeNamer..ctor(String filename) dans D:\Workspace\visualstudio\CasualMeter\Tera.Core\Game\Services\OpCodeNamer.cs:ligne 23
   à CasualMeter.ShellViewModel.HandleMessageReceived(Message obj) dans D:\Workspace\visualstudio\CasualMeter\CasualMeter\ShellViewModel.cs:ligne 568
   à Tera.Sniffing.TeraSniffer.OnMessageReceived(Message message) dans D:\Workspace\visualstudio\CasualMeter\Tera.Sniffing\TeraSniffer.cs:ligne 80
   à Tera.Sniffing.TeraSniffer.HandleMessageReceived(Message message) dans D:\Workspace\visualstudio\CasualMeter\Tera.Sniffing\TeraSniffer.cs:ligne 152
   à Tera.Sniffing.MessageSplitter.OnMessageReceived(Message message) dans D:\Workspace\visualstudio\CasualMeter\Tera.Core\Sniffing\MessageSplitter.cs:ligne 34
   à Tera.Sniffing.MessageSplitter.ClientBlockFinished(Byte[] block) dans D:\Workspace\visualstudio\CasualMeter\Tera.Core\Sniffing\MessageSplitter.cs:ligne 22
   à Tera.PacketLog.BlockSplitter.OnBlockFinished(Byte[] block) dans D:\Workspace\visualstudio\CasualMeter\Tera.Core\PacketLog\Parsing\BlockSplitter.cs:ligne 18
   à Tera.Sniffing.TeraSniffer.HandleClientToServerDecrypted(Byte[] data) dans D:\Workspace\visualstudio\CasualMeter\Tera.Sniffing\TeraSniffer.cs:ligne 164
   à Tera.Sniffing.ConnectionDecrypter.OnClientToServerDecrypted(Byte[] data) dans D:\Workspace\visualstudio\CasualMeter\Tera.Core\Sniffing\ConnectionDecrypter.cs:ligne 31
   à Tera.Sniffing.ConnectionDecrypter.ClientToServer(Byte[] data) dans D:\Workspace\visualstudio\CasualMeter\Tera.Core\Sniffing\ConnectionDecrypter.cs:ligne 85
   à Tera.Sniffing.TeraSniffer.HandleTcpDataReceived(TcpConnection connection, ArraySegment`1 data) dans D:\Workspace\visualstudio\CasualMeter\Tera.Sniffing\TeraSniffer.cs:ligne 143
   à NetworkSniffer.TcpConnection.OnDataReceived(ArraySegment`1 data) dans D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\TcpConnection.cs:ligne 36
   à NetworkSniffer.TcpConnection.HandleTcpReceived(UInt32 sequenceNumber, ArraySegment`1 data) dans D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\TcpConnection.cs:ligne 44
   à NetworkSniffer.TcpSniffer.Receive(ArraySegment`1 ipData) dans D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\TcpSniffer.cs:ligne 61
   à NetworkSniffer.IpSniffer.OnPacketReceived(ArraySegment`1 data) dans D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\IpSniffer.cs:ligne 16
   à NetworkSniffer.IpSnifferWinPcap.device_OnPacketArrival(Object sender, CaptureEventArgs e) dans D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\IpSnifferWinPcap.cs:ligne 108
   à SharpPcap.LibPcap.PcapDevice.SendPacketArrivalEvent(RawCapture p) dans d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\LibPcap\PcapDevice.cs:ligne 262
   à SharpPcap.WinPcap.WinPcapDevice.SendPacketArrivalEvent(RawCapture p) dans d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\WinPcap\WinPcapDevice.cs:ligne 205
   à SharpPcap.LibPcap.PcapDevice.PacketHandler(IntPtr param, IntPtr header, IntPtr data) dans d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\LibPcap\PcapDevice.cs:ligne 360
   à SharpPcap.LibPcap.LibPcapSafeNativeMethods.pcap_dispatch(IntPtr adaptHandle, Int32 count, pcap_handler callback, IntPtr ptr)
   à SharpPcap.LibPcap.PcapDevice.CaptureThread() dans d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\LibPcap\PcapDeviceCaptureLoop.cs:ligne 355
   à System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   à System.Threading.ThreadHelper.ThreadStart()
2016-10-22 00:56:18,354 [1] INFO  CasualMeter.App - Closing.
2016-10-22 01:06:57,537 [1] INFO  CasualMeter.App - Checking for updates.
2016-10-22 01:06:58,053 [1] INFO  CasualMeter.App - Current Version: v1.2.1.14
2016-10-22 01:06:58,538 [1] INFO  CasualMeter.App - Starting up.
2016-10-22 01:07:02,417 [2] ERROR CasualMeter.App - System.DllNotFoundException: Impossible de charger la DLL 'wpcap': Le module spécifié est introuvable. (Exception de HRESULT : 0x8007007E)
   à SharpPcap.WinPcap.SafeNativeMethods.pcap_findalldevs_ex(String source, IntPtr auth, IntPtr& alldevs, StringBuilder errbuf)
   à SharpPcap.WinPcap.WinPcapDeviceList.Devices(String rpcapString, RemoteAuthentication remoteAuthentication) dans d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\WinPcap\WinPcapDeviceList.cs:ligne 123
   à SharpPcap.WinPcap.WinPcapDeviceList.Refresh() dans d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\WinPcap\WinPcapDeviceList.cs:ligne 181
   à SharpPcap.WinPcap.WinPcapDeviceList..ctor() dans d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\WinPcap\WinPcapDeviceList.cs:ligne 77
   à NetworkSniffer.IpSnifferWinPcap.Start() dans D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\IpSnifferWinPcap.cs:ligne 56
   à NetworkSniffer.IpSnifferWinPcap.SetEnabled(Boolean value) dans D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\IpSnifferWinPcap.cs:ligne 43
   à Tera.Sniffing.TeraSniffer.set_Enabled(Boolean value) dans D:\Workspace\visualstudio\CasualMeter\Tera.Sniffing\TeraSniffer.cs:ligne 63
   à CasualMeter.ShellViewModel.<Initialize>b__76_0() dans D:\Workspace\visualstudio\CasualMeter\CasualMeter\ShellViewModel.cs:ligne 265
   à System.Threading.Tasks.Task.InnerInvoke()
   à System.Threading.Tasks.Task.Execute()
2016-10-22 01:10:29,994 [1] INFO  CasualMeter.App - Closing.
2016-10-22 01:10:48,117 [1] INFO  CasualMeter.App - Checking for updates.
2016-10-22 01:10:48,387 [1] INFO  CasualMeter.App - Current Version: v1.2.1.14
2016-10-22 01:10:48,756 [1] INFO  CasualMeter.App - Starting up.
2016-10-22 01:10:48,962 [13] INFO  CasualMeter.Common.UI.ViewModels.CasualViewModelBase - Sniffer has been enabled.
2016-10-22 01:11:48,225 [14] INFO  CasualMeter.Common.UI.ViewModels.CasualViewModelBase - Connected to server Killian.
2016-10-22 01:11:48,258 [14] ERROR CasualMeter.App - System.IO.FileNotFoundException: Le fichier 'C:\Users\Enzo\AppData\Local\CasualMeter\app-1.2.1.14\res\opcodes\306697.txt' est introuvable.
Nom de fichier : 'C:\Users\Enzo\AppData\Local\CasualMeter\app-1.2.1.14\res\opcodes\306697.txt'
   à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   à System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   à System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   à System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   à System.IO.StreamReader..ctor(String path, Encoding encoding)
   à System.IO.File.ReadLines(String path)
   à Tera.Game.OpCodeNamer.ReadOpCodeFile(String filename) dans D:\Workspace\visualstudio\CasualMeter\Tera.Core\Game\Services\OpCodeNamer.cs:ligne 37
   à Tera.Game.OpCodeNamer..ctor(String filename) dans D:\Workspace\visualstudio\CasualMeter\Tera.Core\Game\Services\OpCodeNamer.cs:ligne 23
   à CasualMeter.ShellViewModel.HandleMessageReceived(Message obj) dans D:\Workspace\visualstudio\CasualMeter\CasualMeter\ShellViewModel.cs:ligne 568
   à Tera.Sniffing.TeraSniffer.OnMessageReceived(Message message) dans D:\Workspace\visualstudio\CasualMeter\Tera.Sniffing\TeraSniffer.cs:ligne 80
   à Tera.Sniffing.TeraSniffer.HandleMessageReceived(Message message) dans D:\Workspace\visualstudio\CasualMeter\Tera.Sniffing\TeraSniffer.cs:ligne 152
   à Tera.Sniffing.MessageSplitter.OnMessageReceived(Message message) dans D:\Workspace\visualstudio\CasualMeter\Tera.Core\Sniffing\MessageSplitter.cs:ligne 34
   à Tera.Sniffing.MessageSplitter.ClientBlockFinished(Byte[] block) dans D:\Workspace\visualstudio\CasualMeter\Tera.Core\Sniffing\MessageSplitter.cs:ligne 22
   à Tera.PacketLog.BlockSplitter.OnBlockFinished(Byte[] block) dans D:\Workspace\visualstudio\CasualMeter\Tera.Core\PacketLog\Parsing\BlockSplitter.cs:ligne 18
   à Tera.Sniffing.TeraSniffer.HandleClientToServerDecrypted(Byte[] data) dans D:\Workspace\visualstudio\CasualMeter\Tera.Sniffing\TeraSniffer.cs:ligne 164
   à Tera.Sniffing.ConnectionDecrypter.OnClientToServerDecrypted(Byte[] data) dans D:\Workspace\visualstudio\CasualMeter\Tera.Core\Sniffing\ConnectionDecrypter.cs:ligne 31
   à Tera.Sniffing.ConnectionDecrypter.ClientToServer(Byte[] data) dans D:\Workspace\visualstudio\CasualMeter\Tera.Core\Sniffing\ConnectionDecrypter.cs:ligne 85
   à Tera.Sniffing.TeraSniffer.HandleTcpDataReceived(TcpConnection connection, ArraySegment`1 data) dans D:\Workspace\visualstudio\CasualMeter\Tera.Sniffing\TeraSniffer.cs:ligne 143
   à NetworkSniffer.TcpConnection.OnDataReceived(ArraySegment`1 data) dans D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\TcpConnection.cs:ligne 36
   à NetworkSniffer.TcpConnection.HandleTcpReceived(UInt32 sequenceNumber, ArraySegment`1 data) dans D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\TcpConnection.cs:ligne 44
   à NetworkSniffer.TcpSniffer.Receive(ArraySegment`1 ipData) dans D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\TcpSniffer.cs:ligne 61
   à NetworkSniffer.IpSniffer.OnPacketReceived(ArraySegment`1 data) dans D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\IpSniffer.cs:ligne 16
   à NetworkSniffer.IpSnifferWinPcap.device_OnPacketArrival(Object sender, CaptureEventArgs e) dans D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\IpSnifferWinPcap.cs:ligne 108
   à SharpPcap.LibPcap.PcapDevice.SendPacketArrivalEvent(RawCapture p) dans d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\LibPcap\PcapDevice.cs:ligne 262
   à SharpPcap.WinPcap.WinPcapDevice.SendPacketArrivalEvent(RawCapture p) dans d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\WinPcap\WinPcapDevice.cs:ligne 205
   à SharpPcap.LibPcap.PcapDevice.PacketHandler(IntPtr param, IntPtr header, IntPtr data) dans d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\LibPcap\PcapDevice.cs:ligne 360
   à SharpPcap.LibPcap.LibPcapSafeNativeMethods.pcap_dispatch(IntPtr adaptHandle, Int32 count, pcap_handler callback, IntPtr ptr)
   à SharpPcap.LibPcap.PcapDevice.CaptureThread() dans d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\LibPcap\PcapDeviceCaptureLoop.cs:ligne 355
   à System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   à System.Threading.ThreadHelper.ThreadStart()
2016-10-22 01:16:35,470 [1] INFO  CasualMeter.App - Closing.
2016-10-22 11:51:21,501 [1] INFO  CasualMeter.App - Checking for updates.
2016-10-22 11:51:21,798 [1] INFO  CasualMeter.App - Current Version: v1.2.1.14
2016-10-22 11:51:22,259 [1] INFO  CasualMeter.App - Starting up.
2016-10-22 11:51:22,471 [14] INFO  CasualMeter.Common.UI.ViewModels.CasualViewModelBase - Sniffer has been enabled.
2016-10-22 11:54:28,415 [15] INFO  CasualMeter.Common.UI.ViewModels.CasualViewModelBase - Connected to server Killian.
2016-10-22 11:54:28,449 [15] ERROR CasualMeter.App - System.IO.FileNotFoundException: Le fichier 'C:\Users\Enzo\AppData\Local\CasualMeter\app-1.2.1.14\res\opcodes\306697.txt' est introuvable.
Nom de fichier : 'C:\Users\Enzo\AppData\Local\CasualMeter\app-1.2.1.14\res\opcodes\306697.txt'
   à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   à System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   à System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   à System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   à System.IO.StreamReader..ctor(String path, Encoding encoding)
   à System.IO.File.ReadLines(String path)
   à Tera.Game.OpCodeNamer.ReadOpCodeFile(String filename) dans D:\Workspace\visualstudio\CasualMeter\Tera.Core\Game\Services\OpCodeNamer.cs:ligne 37
   à Tera.Game.OpCodeNamer..ctor(String filename) dans D:\Workspace\visualstudio\CasualMeter\Tera.Core\Game\Services\OpCodeNamer.cs:ligne 23
   à CasualMeter.ShellViewModel.HandleMessageReceived(Message obj) dans D:\Workspace\visualstudio\CasualMeter\CasualMeter\ShellViewModel.cs:ligne 568
   à Tera.Sniffing.TeraSniffer.OnMessageReceived(Message message) dans D:\Workspace\visualstudio\CasualMeter\Tera.Sniffing\TeraSniffer.cs:ligne 80
   à Tera.Sniffing.TeraSniffer.HandleMessageReceived(Message message) dans D:\Workspace\visualstudio\CasualMeter\Tera.Sniffing\TeraSniffer.cs:ligne 152
   à Tera.Sniffing.MessageSplitter.OnMessageReceived(Message message) dans D:\Workspace\visualstudio\CasualMeter\Tera.Core\Sniffing\MessageSplitter.cs:ligne 34
   à Tera.Sniffing.MessageSplitter.ClientBlockFinished(Byte[] block) dans D:\Workspace\visualstudio\CasualMeter\Tera.Core\Sniffing\MessageSplitter.cs:ligne 22
   à Tera.PacketLog.BlockSplitter.OnBlockFinished(Byte[] block) dans D:\Workspace\visualstudio\CasualMeter\Tera.Core\PacketLog\Parsing\BlockSplitter.cs:ligne 18
   à Tera.Sniffing.TeraSniffer.HandleClientToServerDecrypted(Byte[] data) dans D:\Workspace\visualstudio\CasualMeter\Tera.Sniffing\TeraSniffer.cs:ligne 164
   à Tera.Sniffing.ConnectionDecrypter.OnClientToServerDecrypted(Byte[] data) dans D:\Workspace\visualstudio\CasualMeter\Tera.Core\Sniffing\ConnectionDecrypter.cs:ligne 31
   à Tera.Sniffing.ConnectionDecrypter.ClientToServer(Byte[] data) dans D:\Workspace\visualstudio\CasualMeter\Tera.Core\Sniffing\ConnectionDecrypter.cs:ligne 85
   à Tera.Sniffing.TeraSniffer.HandleTcpDataReceived(TcpConnection connection, ArraySegment`1 data) dans D:\Workspace\visualstudio\CasualMeter\Tera.Sniffing\TeraSniffer.cs:ligne 143
   à NetworkSniffer.TcpConnection.OnDataReceived(ArraySegment`1 data) dans D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\TcpConnection.cs:ligne 36
   à NetworkSniffer.TcpConnection.HandleTcpReceived(UInt32 sequenceNumber, ArraySegment`1 data) dans D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\TcpConnection.cs:ligne 44
   à NetworkSniffer.TcpSniffer.Receive(ArraySegment`1 ipData) dans D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\TcpSniffer.cs:ligne 61
   à NetworkSniffer.IpSniffer.OnPacketReceived(ArraySegment`1 data) dans D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\IpSniffer.cs:ligne 16
   à NetworkSniffer.IpSnifferWinPcap.device_OnPacketArrival(Object sender, CaptureEventArgs e) dans D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\IpSnifferWinPcap.cs:ligne 108
   à SharpPcap.LibPcap.PcapDevice.SendPacketArrivalEvent(RawCapture p) dans d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\LibPcap\PcapDevice.cs:ligne 262
   à SharpPcap.WinPcap.WinPcapDevice.SendPacketArrivalEvent(RawCapture p) dans d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\WinPcap\WinPcapDevice.cs:ligne 205
   à SharpPcap.LibPcap.PcapDevice.PacketHandler(IntPtr param, IntPtr header, IntPtr data) dans d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\LibPcap\PcapDevice.cs:ligne 360
   à SharpPcap.LibPcap.LibPcapSafeNativeMethods.pcap_dispatch(IntPtr adaptHandle, Int32 count, pcap_handler callback, IntPtr ptr)
   à SharpPcap.LibPcap.PcapDevice.CaptureThread() dans d:\Workspace\visualstudio\lib\SharpPcap\SharpPcap\LibPcap\PcapDeviceCaptureLoop.cs:ligne 355
   à System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   à System.Threading.ThreadHelper.ThreadStart()

**Comment by Gl0** [comment]
Wait for next version release.

**Comment by lunyx** [comment]
Sorry for the delay, I was on vacation. Just released 1.2.2.0 which should resolve this as well as another bug that caused some crashes.
