### ISSUE TITLE
does not even have an overlay now.

### ISSUE THREAD

**Issue by Goodiehao** [lunyx/CasualMeter#12]
as title

**Comment by lunyx** [comment]
Can you post the contents of your settings file located at %AppData%\CasualMeter\?

**Comment by Goodiehao** [comment]
as requested its 
{
  "WindowLeft": "NaN",
  "WindowTop": "NaN",
  "Opacity": 1.0,
  "UiScale": 1.0,
  "IsPinned": true,
  "HotKeys": {
    "Modifier": "Control",
    "PasteStats": "Insert",
    "Reset": "Delete",
    "SaveAndReset": "End"
  }
}

**Comment by lunyx** [comment]
Try setting the WindowLeft and WindowTop to 100 without quotes.  These values should be set automatically, but that might be a bug.  Let me know if that fixes the issue.

**Comment by Goodiehao** [comment]
it does not work.

**Comment by lunyx** [comment]
Install WinPCap or reinstall it if you already have it.

**Comment by Goodiehao** [comment]
alright reinstalling WinPCap solved the problem
