### ISSUE TITLE
Casual Meter crashing

### ISSUE THREAD

**Issue by Nayroy** [lunyx/CasualMeter#122]
Casual Meter crashed when entering server, AV in NA in my case. I have WinPcap installed and have set to automatically run, no VPN. I run Casual Meter, then launch TERA, if more info is needed, I will try my best to get it.

**Comment by happikush** [comment]
I'm encountering same issue. Fey Forest in NA here.

There seems to be missing files with the latest update? Not sure, but here's the logs.

`016-10-29 07:20:55,148 [3] ERROR CasualMeter.App - System.IO.FileNotFoundException: Could not find file 'C:\Users\<username>\AppData\Local\CasualMeter\app-1.2.1.14\res\opcodes\306697.txt'.`

**Comment by Gl0** [comment]
While lunyx is away from here and can't push update to users - refreshed [my fork](https://github.com/Gl0/CasualMeter/releases) which have the only difference - disabled autoupdate.

**Comment by happikush** [comment]
@Gl0 Thanks as usual for the super fast response! The version you made worked perfectly for me.

**Comment by adem940** [comment]
thanks Gl0 :)

**Comment by lunyx** [comment]
Sorry for the delay, I was on vacation.  Just released 1.2.2.0 which should resolve this as well as another bug that caused some crashes.
