### ISSUE TITLE
"Count only bosses" Not working after Archer Revamp Update

### ISSUE THREAD

**Issue by screwystein** [lunyx/CasualMeter#125]
Seems they changed whatever identifier, or packet that you track for "bosses." If you could look into it, that'd be great. :)

**Comment by lunyx** [comment]
No issues here with detecting bosses.  What are your settings and how is it "not working"?

**Comment by screwystein** [comment]
![casual meter](https://cloud.githubusercontent.com/assets/24358202/20861002/0ea18e0e-b953-11e6-8305-bb0f778279d6.PNG)
Here's my listed settings. When entering a boss fight, the only way I can get the meter to register DPS with the "count only bosses" option enabled is well; by disabling it and letting it counting everything. Before this update it worked, maybe you've updated and I haven't seen it? 
I'm using GI0's version 1.2.2.1B.

**Comment by Gl0** [comment]
Just rechecked, 1.2.2.1B have no problems detecting bosses and counting only them. (It's quite outdated, works only on RU for now - better ask questions on RU forum/my issues page)

**Comment by screwystein** [comment]
What do you mean it works only on RU?

**Comment by Gl0** [comment]
Last time it was updated when RU received 30-raid patch. All other regions received new patches later.
One of the things that changed (except new skills/monsters/abnormals) is structure of spawn npc packet. If you are using it on any region other than RU - it's outdated and can't detect any monster at all.
