### ISSUE TITLE
Can not install

### ISSUE THREAD

**Issue by tehfreaks** [lunyx/CasualMeter#126]
the link http://lunyx.net/CasualMeter/Setup.exe does not work. I download the CasualMeter-master zip file but it does not contain an .exe or setup file. Instructions on installation would be appreciated.

**Comment by tehfreaks** [comment]
Does anyone keep up with this site?

**Comment by Gl0** [comment]
Site owner is away now and can't fix it. Probably he will be back after weekend.
You have downloaded source code, you need MS Visual Studio to compile it.

**Comment by tehfreaks** [comment]
Thanks I found my old setup file download file. But it will not launch. I have used the updater as well. Has there been an patch that broke it until it is updated again?

**Comment by Gl0** [comment]
If your setup.exe is older than date of last patch in your server - it wouldn't work even if you unpack it manually. Update is working via the same site as download, so it will be working only when site will be back online. 
You may try to combine your version of Casual with Tera.Core.dll and fresh database from latest shinrameter. If your Casual is not too old - it will work fine.

**Comment by Etherblock** [comment]
I'm having the same problem as Tehfreaks. Is there any chance you could put the setup files on Google Drive or Dropbox and give us the Download link? i really wanna use this but I cant access the website for the files

**Comment by Gl0** [comment]
Updated [my fork](https://github.com/Gl0/CasualMeter/releases) that have only one difference - disabled autoupdate.

**Comment by tehfreaks** [comment]
Thanks, works great

**Comment by Gl0** [comment]
Don't forget to go back to original installer version when site comes back online or you will need to check for updates manually.

**Comment by lunyx** [comment]
I'm not sure why the web hosting keeps crashing as the server itself is still up.  I'll try to investigate this more, but for now, it's back up.

**Comment by lunyx** [comment]
Updated to new host.
