### ISSUE TITLE
Window's size problem

### ISSUE THREAD

**Issue by olololopetrusha** [lunyx/CasualMeter#129]
Hi! After uninstal and install Raptr, casual meter window's size became the full width of the screen. Size of main window i cant change. Please help to fix.

![2f2](https://cloud.githubusercontent.com/assets/24804811/21515711/16fdc5a6-cce3-11e6-8927-6c51b7a2e2ad.png)

**Comment by adem940** [comment]
it always happens like that, don't worry about it, it will still show small window when you go with party, this has always been like this, it seems you just realized it.
