### ISSUE TITLE
Unable to download the program

### ISSUE THREAD

**Issue by silverquil** [lunyx/CasualMeter#130]
Whenever I try to access http://lunyx.net/CasualMeter/Setup.exe I get 

This site can’t be reached
lunyx.net took too long to respond.

Is there an alternative link to download casual meter?

**Comment by adem940** [comment]
meter itself doesn't work for a couple of days now, I guess the owner is busy and didn't check the site.

**Comment by lunyx** [comment]
Meter itself should start up after a while once it times out.  Looks like I'm still having issues with this service provider, so I may just switch to another one soon.

**Comment by lunyx** [comment]
Also, the site is back up now.  Seems like they resolved whatever it is on their end for now.  If there's another outage of this scale, I'll switch to a new provider.  Sorry for the inconvenience.
