### ISSUE TITLE
PASTE PROBLEM

### ISSUE THREAD

**Issue by harrypoter55** [lunyx/CasualMeter#143]
Hello

i dont know every key is working , RESET + SAVE but paste doesnt work

any solution please

**Comment by Gl0** [comment]
open chat for text input before pressing hotkey

**Comment by harrypoter55** [comment]
i open chat and i make ctrl + insert but nothing past

**Comment by Gl0** [comment]
check `%appdata%\CasualMeter\logs\CasualMeter.log`, may be that hotkey is already in use by some other app.
