### ISSUE TITLE
Can't Uninstall

### ISSUE THREAD

**Issue by ashjnr** [lunyx/CasualMeter#148]
I am deleting everything but after restart my computer it shows up again. What should i do?

**Comment by adem940** [comment]
then it is about your pc, try to uninstall with iObit uninstaller, go to installation folder, right click on exe and click ''uninstall with iObit''

**Comment by ashjnr** [comment]
I tried it but no change..

**Comment by adem940** [comment]
you sure there is no file protection thingie installed on your pc?

**Comment by Gl0** [comment]
https://github.com/lunyx/CasualMeter/wiki#uninstall

**Comment by ashjnr** [comment]
@adem940 Yep there is nothing
@Gl0 Tried but not working..

**Comment by lunyx** [comment]
All the installer does is save some files to appdata folders.  If you've deleted the files, there's no way for the application to start up.
