### ISSUE TITLE
Meter not connecting to server?

### ISSUE THREAD

**Issue by darlingv2** [lunyx/CasualMeter#152]
I have casual meter installed it loads up fine, shows up on my screen but it won't connect to my server despite uninstalling and reinstalling a couple of times tried going from server list to my server and opening it before I launcher/client, but damage numbers still won't pop up and it never says it's connected to my server. How do I get it to connect?

**Comment by Gl0** [comment]
You can follow network part of [guide](https://github.com/neowutran/ShinraMeter/wiki#prerequisite) 
(3.3 is done via checkbox in casualmeter settings and restart.)
