### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by Nayroy** [lunyx/CasualMeter#158]
Program is constantly crashing.
Log. https://pastebin.com/BBWXmtXW
[CasualMeter.log](https://github.com/lunyx/CasualMeter/files/1608748/CasualMeter.log)

Windows 7 x64 SP1
i7 2600
GTX 970
8GB DRAM

**Comment by Gl0** [comment]
Seems it fails autoupdate. Install update manually via setup.exe

**Comment by Nayroy** [comment]
I don't see setup.exe. Is it in any of the folders created by Casual Meter or a download on github?

**Comment by Nayroy** [comment]
It's working now. Thanks.
