### ISSUE TITLE
Crash on Exit (Win10)

### ISSUE THREAD

**Issue by reloxx13** [lunyx/CasualMeter#16]
On Windows 10 64bit the Meter Crashes when clicking on the "X" or on Exit in the Taskbar.

Logs in AppData dir are empty :(

I get this in Windows logs:

> Name der fehlerhaften Anwendung: CasualMeter.exe, Version: 1.0.0.0, Zeitstempel: 0x56455230
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.10240.16384, Zeitstempel: 0x559f3b2a
Ausnahmecode: 0xc000041d
Fehleroffset: 0x000b3e28
ID des fehlerhaften Prozesses: 0x17d0
Startzeit der fehlerhaften Anwendung: 0x01d12259434926f3
Pfad der fehlerhaften Anwendung: C:\Users\MYNAME\AppData\Local\Apps\2.0\38R88MX3.K67\KAQ0Y1YY.BCK\casu..tion_20d6e3ba73542d2e_0001.0000_dc93863583781e7c\CasualMeter.exe
Pfad des fehlerhaften Moduls: C:\Windows\SYSTEM32\KERNELBASE.dll
Berichtskennung: 74467a4b-22bb-4be3-a5ba-abb21f360495
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:

**Comment by lunyx** [comment]
It seems to occur when you immediately move focus elsewhere before it's fully exited, is that correct?  I recall this happening in the other open source meters as well.

**Comment by reloxx13** [comment]
Yep, only crashes if u loose focus after click, and not loosing focus takes long time till close...

**Comment by lunyx** [comment]
Should be fixed now with latest version.
