### ISSUE TITLE
Old App in AppData after Update

### ISSUE THREAD

**Issue by reloxx13** [lunyx/CasualMeter#17]
If i download the newest version (setup.exe) and install it, the old version is still in AppData.

Also its very unusual that the installed app is installed in AppData.

the Path is of the exe file is:
> C:\Users\MYNAME\AppData\Local\Apps\2.0\38R88MX3.K67\KAQ0Y1YY.BCK\casu..tion_20d6e3ba73542d2e_0001.0000_cdcb69db19a444bc

As exemple, the old app is still their in path:
> C:\Users\MYNAME\AppData\Local\Apps\2.0\38R88MX3.K67\KAQ0Y1YY.BCK\casu..tion_20d6e3ba73542d2e_0001.0000_dc93863583781e7c

Their are also just empty folders in here:
> C:\Users\MYNAME\AppData\Local\Apps\2.0\Data

Windows10 64bit

**Comment by lunyx** [comment]
Ask Microsoft why they do that.

**Comment by reloxx13** [comment]
It did never update alone for me.

**Comment by reloxx13** [comment]
Microsoft said, u r not building the app correctly.
