### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by eduedp** [lunyx/CasualMeter#29]
Tray icon is shown, but casualmeter window not.
Log shows this error:

2015-12-01 23:12:27,179 [1] INFO  CasualMeter.App - Starting up.
2015-12-01 23:12:27,520 [1] ERROR CasualMeter.App - System.BadImageFormatException: Não foi possível carregar arquivo ou assembly 'NetworkSniffer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' ou uma de suas dependências. O módulo deveria conter um manifesto de assembly.
Nome do arquivo: 'NetworkSniffer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   em Tera.Sniffing.TeraSniffer..ctor(IEnumerable`1 servers)
   em CasualMeter.ShellViewModel.Initialize()
   em CasualMeter.ShellView.OnInitialized(EventArgs e)
   em System.Windows.FrameworkElement.TryFireInitialized()
   em System.Windows.FrameworkElement.EndInit()
   em MS.Internal.Xaml.Runtime.ClrObjectRuntime.InitializationGuard(XamlType xamlType, Object obj, Boolean begin)

AVI: o log de associações de assembly está desativado.
Para ativar o log de  falhas de assembly, defina o valor do Registro [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) como 1.
Observação: há alguma penalidade para o desempenho associada ao log de falha de associação de assembly.
Para desativar esse recurso, remova o valor do Registro [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by lunyx** [comment]
Try reinstalling.  Seems like a file was deleted, probably by antivirus.

**Comment by eduedp** [comment]
I tried disabling antivirus and reinstalling.
But the same error still occurs.

**Comment by eduedp** [comment]
I have .NET Framework 4.5.2 installed. That's not a problem, right?

**Comment by lunyx** [comment]
Use the new download link on the main page and try again.

**Comment by eduedp** [comment]
Downloaded the new setup, but still not working.
Now I think its because of TERAs new version.
When will it be updated?

**Comment by lunyx** [comment]
It's updated now.

**Comment by eduedp** [comment]
Working again. Thank you very much!!!
