### ISSUE TITLE
Count backcrits stat

### ISSUE THREAD

**Issue by Owyn** [lunyx/CasualMeter#31]
Is it possible to determinate if a hit was a backhit? - probably not

But I think it's possible to detect backCrits:

all DD players wear  Forceful niveots,
so when a player with it backcrit - right after it he receives a refreshed 10 sec status effect buff of the forceful niveot, I believe for each backcrit,
so if you count those effect refreshes and mark previous hits as backcrits it would be possible to count them and display stats " percent of backcrits out of total crits" - a pretty important and informative DPS debugging stat,
information about other players and their buffs is also sent to each client as we can see those in party window so it can be counted for everyone in the party.

P.S. - submitted my idea at https://github.com/gothos-folly/TeraDamageMeter/issues/19 also

**Comment by lunyx** [comment]
I'm not going to work on this unless there's a reliable method of determining whether or not a hit is made from the back.  As far as I'm aware, this data isn't present in any specific packet and would require some guess as to how it's calculated.  Feel free to reopen this issue if there's a solid, accurate way of determining this information.
