### ISSUE TITLE
Doesn't work after 12/8/15 update.

### ISSUE THREAD

**Issue by Polar509** [lunyx/CasualMeter#38]
Myself and others are having issues with the casual meter not recording any damage at all when in game. It says it connects to correct server (MT) but the damage is not recorded. Worked fine before patch. Any help would be appreciated.

**Comment by luxtau** [comment]
Wait for browler update approval: https://github.com/lunyx/CasualMeter/pull/39

**Comment by lunyx** [comment]
I merged it in, should work now.  Please close the issue if it's working.

**Comment by lunyx** [comment]
Seems like many other people have confirmed that it's working now, so I'm closing this.
