### ISSUE TITLE
counts self-damage

### ISSUE THREAD

**Issue by Gl0** [lunyx/CasualMeter#4]
Your fix for DFA doesn't fix Command: Self-destruct, counting 10M useless damage per hit

**Comment by lunyx** [comment]
I'll take a look at it when I have a gunner friend available to test.

**Comment by lunyx** [comment]
I already have this fixed and ready to go.  It'll be released along with encounters in the next version.

**Comment by Gl0** [comment]
Haven't compile your source (no vs2015 here), but
`!(skillResultMessage.Target.Equals(skillResultMessage.Source) && !skillResultMessage.IsHeal))` 
will count extra damage, done by robot to turrel

**Comment by lunyx** [comment]
I'm not quite sure what you mean by that.  That will ignore any result with the same target and source entity that isn't a heal (so self destruct is damage dealt to self and is ignored).  Perhaps you could explain it differently?

**Comment by Gl0** [comment]
They are different entites with the same owner. Try to summon turrel and robot, place them near each other, then use self-destruct, and you will see what I mean

**Comment by lunyx** [comment]
I'll give it a try when I can.  I actually hadn't tested the case if both of them were both up.

**Comment by lunyx** [comment]
Have you tried this yourself?  There's no damage being recorded when you self-destruct them near each other.

**Comment by Gl0** [comment]
Hm... Now I can't reproduce this... I remember, that I saw different entity id's when debugging while fixing this extra damage, and wrote this expression via 
`UserEntity.ForEntity(message.Source)` to overcome this.
May be there have to be some other condition to get this effect.
