### ISSUE TITLE
Meter dont Work after New Game Update with Stormfury

### ISSUE THREAD

**Issue by Kakashi82** [lunyx/CasualMeter#46]
Dmg will not been Displayed on the Meter? whats happend ?
Meter has no autoupdate ?

**Comment by reloxx13** [comment]
It works, update manual if it does not update.

**Comment by lunyx** [comment]
You probably have the old clickonce version.  Download the latest installer.  You can uninstall the old version using Add or Remove Programs in the Control Panel.
