### ISSUE TITLE
Connection isn't established

### ISSUE THREAD

**Issue by livwad** [lunyx/CasualMeter#48]
Hi, your program opens perfectly but It doesn't connect to the server.
I have WinPCap 4.1.3 installed. I use a wired ethernet connection and no VPNs. I don't open Tera through Steam. The npf driver is running. If the server I play on makes a difference, it's Tempest Reach.

The logs end when the Sniffer is enabled.
2015-12-27 17:04:19,655 [1] INFO  CasualMeter.App - Checking for updates.
2015-12-27 17:04:19,825 [1] INFO  CasualMeter.App - Current Version: v1.0.6.6
2015-12-27 17:04:22,211 [1] INFO  CasualMeter.App - Starting up.
2015-12-27 17:04:26,087 [1] INFO  CasualMeter.ShellViewModel - Sniffer has been enabled.

**Comment by lunyx** [comment]
How are you determining that it hasn't connected to the server?  If you see that message, it means you're already connected.

**Comment by livwad** [comment]
Running Tera and logging in/engaging in battle causes no change to the interface.

**Comment by lunyx** [comment]
I'd try reinstalling WinPCap (uninstalling and installing again), then restarting your computer.

**Comment by livwad** [comment]
No change, logs stayed the same, interface still not saying it's connected. Would my geographical location cause any weird difficulties?

**Comment by lunyx** [comment]
No, that shouldn't cause any issues.  Can you use Resource Monitor (google if you don't have if it's not already installed with Windows) and see what IP address TERA is connecting to under network activity?  If you can't figure it out, I can go a into a bit more detail.

**Comment by livwad** [comment]
Remote Address: 98.158.184.68 I'm assuming this is the IP it's connecting to as the only other shown address is my own Local one.

**Comment by livwad** [comment]
Nevermind. Found a sneaky old program used back a while ago. Will uninstall and see if it works then.
