### ISSUE TITLE
Display "0" instead of NaN

### ISSUE THREAD

**Issue by reloxx13** [lunyx/CasualMeter#5]
If u get a heal and did not made any damge before, the Meter will show up the Username with heal, but instead of 0 DMG it shows NaN (not a number).

Good work, go on :3
![meter_e1](https://cloud.githubusercontent.com/assets/14855001/11075277/b7e6e4fa-87f4-11e5-8c95-3cbb27697d88.png)

**Comment by lunyx** [comment]
That's a design choice as your contribution isn't 0 since there was no fight.  Also, this should not be occurring in the latest version since it no longer picks up heals before fights are started.

**Comment by reloxx13** [comment]
Heya,

okay, got the latest version now and it only occurs on shown crits "Crits: NaN".
