### ISSUE TITLE
Installation has failed 

### ISSUE THREAD

**Issue by Movoxo** [lunyx/CasualMeter#54]
Get this when trying to install 
10436> 2015-12-29 04:37:48> Program: Starting Squirrel Updater: --install .
10436> 2015-12-29 04:37:49> Program: Starting install, writing to C:\Users\ADMIN\AppData\Local\SquirrelTemp
10436> 2015-12-29 04:37:50> Program: About to install to: C:\Users\ADMIN\AppData\Local\Discord
10436> 2015-12-29 04:37:50> SingleGlobalInstance: Grabbing lockfile with timeout of 00:00:10
10436> 2015-12-29 04:37:50> CheckForUpdateImpl: Reading RELEASES file from C:\Users\ADMIN\AppData\Local\SquirrelTemp
10436> 2015-12-29 04:37:51> CheckForUpdateImpl: Remote version 0.0.283 differs from local 
10436> 2015-12-29 04:37:51> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
10436> 2015-12-29 04:37:51> ApplyReleasesImpl: Writing files to app directory: C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283
10436> 2015-12-29 04:37:59> ApplyReleasesImpl: Moving file C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\lib\net45\app.ico to C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\app.ico
10436> 2015-12-29 04:37:59> ApplyReleasesImpl: Moving file C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\lib\net45\client.x86.dll to C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\client.x86.dll
10436> 2015-12-29 04:37:59> ApplyReleasesImpl: Moving file C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\lib\net45\content_resources_200_percent.pak to C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\content_resources_200_percent.pak
10436> 2015-12-29 04:37:59> ApplyReleasesImpl: Moving file C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\lib\net45\content_shell.pak to C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\content_shell.pak
10436> 2015-12-29 04:37:59> ApplyReleasesImpl: Moving file C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\lib\net45\d3dcompiler_47.dll to C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\d3dcompiler_47.dll
10436> 2015-12-29 04:37:59> ApplyReleasesImpl: Moving file C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\lib\net45\Discord.exe to C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\Discord.exe
10436> 2015-12-29 04:37:59> ApplyReleasesImpl: Moving file C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\lib\net45\icudtl.dat to C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\icudtl.dat
10436> 2015-12-29 04:37:59> ApplyReleasesImpl: Moving file C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\lib\net45\libdiscord.dll to C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\libdiscord.dll
10436> 2015-12-29 04:37:59> ApplyReleasesImpl: Moving file C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\lib\net45\inject.x64.exe to C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\inject.x64.exe
10436> 2015-12-29 04:37:59> ApplyReleasesImpl: Moving file C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\lib\net45\libEGL.dll to C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\libEGL.dll
10436> 2015-12-29 04:37:59> ApplyReleasesImpl: Moving file C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\lib\net45\libGLESv2.dll to C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\libGLESv2.dll
10436> 2015-12-29 04:37:59> ApplyReleasesImpl: Moving file C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\lib\net45\msvcr120.dll to C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\msvcr120.dll
10436> 2015-12-29 04:37:59> ApplyReleasesImpl: Moving file C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\lib\net45\msvcp120.dll to C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\msvcp120.dll
10436> 2015-12-29 04:37:59> ApplyReleasesImpl: Moving file C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\lib\net45\node.dll to C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\node.dll
10436> 2015-12-29 04:37:59> ApplyReleasesImpl: Moving file C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\lib\net45\pdf.dll to C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\pdf.dll
10436> 2015-12-29 04:37:59> ApplyReleasesImpl: Moving file C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\lib\net45\natives_blob.bin to C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\natives_blob.bin
10436> 2015-12-29 04:37:59> ApplyReleasesImpl: Moving file C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\lib\net45\server.x86.dll to C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\server.x86.dll
10436> 2015-12-29 04:37:59> ApplyReleasesImpl: Moving file C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\lib\net45\snapshot_blob.bin to C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\snapshot_blob.bin
10436> 2015-12-29 04:37:59> ApplyReleasesImpl: Moving file C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\lib\net45\Squirrel.exe to C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\Squirrel.exe
10436> 2015-12-29 04:37:59> ApplyReleasesImpl: Moving file C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\lib\net45\ui_resources_200_percent.pak to C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\ui_resources_200_percent.pak
10436> 2015-12-29 04:37:59> ApplyReleasesImpl: Moving file C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\lib\net45\vccorlib120.dll to C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\vccorlib120.dll
10436> 2015-12-29 04:37:59> ApplyReleasesImpl: Moving file C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\lib\net45\client.x64.dll to C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\client.x64.dll
10436> 2015-12-29 04:37:59> ApplyReleasesImpl: Moving file C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\lib\net45\xinput1_3.dll to C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\xinput1_3.dll
10436> 2015-12-29 04:38:06> ApplyReleasesImpl: Started updateSelf pid 12780
10436> 2015-12-29 04:38:07> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\Discord.exe]
10436> 2015-12-29 04:38:13> Utility: Process Started: C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\Discord.exe --squirrel-install 0.0.283, pid 6780
10436> 2015-12-29 04:38:26> Utility: Received exitcode -1073740940 from process C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\Discord.exe
10436> 2015-12-29 04:38:26> ApplyReleasesImpl: ran C:\Users\ADMIN\AppData\Local\Discord\app-0.0.283\Discord.exe, pid 16368
10436> 2015-12-29 04:38:26> ApplyReleasesImpl: Starting fixPinnedExecutables
10436> 2015-12-29 04:38:26> ApplyReleasesImpl: fixPinnedExecutables: newCurrentFolder: app-0.0.283
10436> 2015-12-29 04:38:26> ApplyReleasesImpl: fixPinnedExecutables: enumerating path C:\Users\ADMIN\AppData\Roaming\Microsoft\Windows\Start Menu failed: System.UnauthorizedAccessException: Toegang tot het pad C:\Users\ADMIN\AppData\Roaming\Microsoft\Windows\Start Menu\Programma's is geweigerd.
   bij System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bij System.IO.FileSystemEnumerableIterator`1.AddSearchableDirsToStack(SearchData localSearchData)
   bij System.IO.FileSystemEnumerableIterator`1.MoveNext()
   bij System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bij System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)
   bij System.IO.DirectoryInfo.GetFiles(String searchPattern, SearchOption searchOption)
   bij Squirrel.UpdateManager.ApplyReleasesImpl.fixPinnedExecutables(SemanticVersion newCurrentVersion)
10436> 2015-12-29 04:38:26> ApplyReleasesImpl: Updating shortcut C:\Users\ADMIN\Desktop\Discord.lnk
10436> 2015-12-29 04:38:26> ApplyReleasesImpl: Fixing up tray icons
10436> 2015-12-29 04:38:26> ApplyReleasesImpl: cleanDeadVersions: for version 0.0.283
10436> 2015-12-29 04:38:26> ApplyReleasesImpl: cleanDeadVersions: exclude current version folder app-0.0.283

**Comment by lunyx** [comment]
Doesn't look like an error, nor am I responsible for installer errors.
