### ISSUE TITLE
Can it works on Taiwan server? Please i can help anything you want.

### ISSUE THREAD

**Issue by ericcheng26** [lunyx/CasualMeter#56]
Please i can help anything you want.

**Comment by lunyx** [comment]
Read this section: https://github.com/lunyx/CasualMeter#development

**Comment by ericcheng26** [comment]
i have read it already. But still don't know what should i do.

**Comment by Gl0** [comment]
new TW opcodes is available at https://github.com/neowutran/TeraDpsMeterData/tree/master/opcodes
So you need to download opcodes-TW.txt to res directory and add
`220.228.174.67 TW 爾雷曼西亞
220.228.174.68 TW 貝利卡`
to servers.txt in it

**Comment by lunyx** [comment]
This has been added in.
