### ISSUE TITLE
Constant crashing (fixed)

### ISSUE THREAD

**Issue by Rases** [lunyx/CasualMeter#62]
> 2016-02-21 01:16:16,751 [1] INFO  CasualMeter.App - Checking for updates.
> 2016-02-21 01:16:16,767 [1] INFO  CasualMeter.App - Current Version: v1.0.8.1
> 2016-02-21 01:16:18,891 [1] INFO  CasualMeter.App - Starting up.
> 2016-02-21 01:16:19,159 [14] INFO  CasualMeter.ShellViewModel - Sniffer has been enabled.
> 2016-02-21 01:16:36,166 [3] INFO  CasualMeter.ShellViewModel - Sniffer has been disabled.
> 2016-02-21 01:16:36,187 [3] INFO  CasualMeter.ShellViewModel - Sniffer has been enabled.
> 2016-02-21 01:16:38,188 [16] INFO  CasualMeter.ShellViewModel - Sniffer has been disabled.
> 2016-02-21 01:16:46,509 [2] ERROR CasualMeter.App - System.Net.Sockets.SocketException (0x80004005): An attempt was made to access a socket in a way forbidden by its access permissions
>    at System.Net.Sockets.Socket..ctor(AddressFamily addressFamily, SocketType socketType, ProtocolType protocolType)
>    at NetworkSniffer.IpSnifferRawSocketSingleInterface.Init() in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\IpSnifferRawSocketSingleInterface.cs:line 30
>    at NetworkSniffer.IpSnifferRawSocketSingleInterface.SetEnabled(Boolean value) in D:\Workspace\visualstudio\CasualMeter\NetworkSniffer\IpSnifferRawSocketSingleInterface.cs:line 68
>    at Tera.Sniffing.TeraSniffer.set_Enabled(Boolean value) in D:\Workspace\visualstudio\CasualMeter\Tera.Sniffing\TeraSniffer.cs:line 56
>    at CasualMeter.ShellViewModel.<Initialize>b__55_0() in D:\Workspace\visualstudio\CasualMeter\CasualMeter\ShellViewModel.cs:line 221
>    at System.Threading.Tasks.Task.InnerInvoke()
>    at System.Threading.Tasks.Task.Execute()
> 

**Nevermind, Fixed it, was being dumb myself.**

**Comment by lunyx** [comment]
In case anyone else stumbles on this, it's because it wasn't run as an administrator while using raw sockets mode.
