### ISSUE TITLE
Port down to Framework 4.0?

### ISSUE THREAD

**Issue by Kagurame** [lunyx/CasualMeter#66]
Hi,

i just wondering if it possible to port the application down to .NET Framework 4.0
For working purposes i cant use .NET Framework 4.5 or higher on my computer - so i cant use the software in this case.

So im wondering (as i said) if a downport if possible (i would do it via fork as example) or if the dependecies or something similar strictly require the .NET 4.5 (+) Framework

Regards

**Comment by lunyx** [comment]
Try it yourself, you'd have a lot of work ahead of you in any case.
