### ISSUE TITLE
Meter doesn't work since EU Update

### ISSUE THREAD

**Issue by ThatGuyEUW** [lunyx/CasualMeter#69]
Title explains it all :)

**Comment by NiponM** [comment]
It doesnt work after the last NA update.

**Comment by Gl0** [comment]
You can update meter databases manually while lunyx is away from here.
Just download https://github.com/neowutran/TeraDpsMeterData/archive/master.zip and extract it to res subdir in meter folder, overwriting all content (valid for versions 1.1.0.1+ ).

**Comment by lunyx** [comment]
It's updated now.
