### ISSUE TITLE
Issues with Fullscreen TERA

### ISSUE THREAD

**Issue by darkconcept** [lunyx/CasualMeter#7]
If you set TERA in Fullscreen, meter doesn't stay on top. If you have dualscreen, you can always set Windowed Fullscreen, move meter to the next desktop and go back to Fullscreen. Meter will save its position for the next time, so you don't have to move it again. 

Problem comes when you double-click to see skills info, the new window always appears in the same place (TERA Fullscreen window). No matter where you move it, if you close it and open it again, skills info window doesn't save any position, because it's a new one I guess.

Obviously you can fix all these just by playing in Windowed Fullscreen setting, but it's known that you lose some performance with this setup.

Maybe there's something you can do about this.

**Comment by lunyx** [comment]
I'm not going to bother with making it work in full screen because it's vastly more complicated to do so and beyond my scope of knowledge.  However, the location for which the skill breakdown shows up bothers me as well, so I will probably set it to a location relative to where the meter is at.

**Comment by lunyx** [comment]
New windows will now show up near the center of the current screen of the meter, and additional ones will cascade down from that one.
