### ISSUE TITLE
Allow us to choose server as well

### ISSUE THREAD

**Issue by Vysse** [lunyx/CasualMeter#70]
This way if Tera is launched we don't have to re-launch Tera to get the meter if it crashes or we forget to launch it.

**Comment by lunyx** [comment]
That's not how it works.  It doesn't make a difference if you can choose server or not.

**Comment by Vysse** [comment]
Is there no way to solve this then?

**Comment by Gl0** [comment]
The only way is to keep some sniffer running all the time, capturing login packets and storing keys, so that newly started meter could read and use the latest one.
