### ISSUE TITLE
[project structure][idea] Common Tera project between different meter

### ISSUE THREAD

**Issue by neowutran** [lunyx/CasualMeter#74]
Your project "Tera.Core" and my project "Tera" is pretty much the same thing. Casual Meter, Shinra Meter and every other meter need this project to work. And it's not meter specific

What about a common github repository? (integrated with git submodule into our meter)

**Comment by lunyx** [comment]
I'll have to check the differences we have first.  I believe I've made some modifications to the project before, so I'm not sure if it'll impact anything.

**Comment by neowutran** [comment]
yep ^^ if you want, the project is here: https://github.com/neowutran/Tera

**Comment by Gl0** [comment]
There different monster database to npcentity connection realization.
For casual I used gothos structures https://github.com/lunyx/CasualMeter/blob/master/Tera.Core/Game/NpcInfo.cs
Skill and monster databases are also in Tera.Game (services). It's simpler to have them unificated.

**Comment by neowutran** [comment]
ok, I will change that then

**Comment by Gl0** [comment]
To make common structure we need to add zone name to https://github.com/lunyx/CasualMeter/blob/master/Tera.Core/Game/Services/NpcDatabase.cs#L25 and NpcInfo.cs
And delete obsolete
https://github.com/lunyx/CasualMeter/blob/master/Tera.Core/Game/Services/SkillDatabase.cs#L24
since all overrides should be done via common multilanguage xml files.

**Comment by Gl0** [comment]
merged all staff https://github.com/neowutran/Tera/commit/6ea251559b84acd19de1bf879263a271e35330c7

**Comment by Gl0** [comment]
Seems ended merging and cleanup.

**Comment by lunyx** [comment]
@Gl0 Do you have any issues with updating submodule?  It's not pulling for me, regardless of what I try.

**Comment by Gl0** [comment]
I prefer to go to submodule directory in git shell and do regularly git pull from there
Or you can use git submodule update --remote -merge

**Comment by lunyx** [comment]
I've tried both of those prior to your post, but it doesn't update anything.  It just says it's already up to date with no files in either directory.

**Comment by Gl0** [comment]
if there is no files just do 
git submodule init

**Comment by lunyx** [comment]
Already did that as well.

**Comment by Gl0** [comment]
git submodule init
+
git submodule update
should pull all files there

**Comment by Gl0** [comment]
seems you have something wrong with CasualMeter\res.
It have broken link even on github

**Comment by Gl0** [comment]
Seems it was my fault when I was updating lx branch

**Comment by lunyx** [comment]
I readded both and it fixed the issue.

**Comment by Gl0** [comment]
yup, didn't saw this, cause submodule was properly inited in main branch
sorry
