### ISSUE TITLE
no show me dps meter

### ISSUE THREAD

**Issue by Rubenfarfan** [lunyx/CasualMeter#85]
hi, i have problem with casual meter, is not display me dps, just said, casual meter- NA but is not working. 
i install wincap them casual meter but is not display me anything.
![sin titulo](https://cloud.githubusercontent.com/assets/4439844/14231313/ab0baf5a-f93b-11e5-8165-9b84cc795858.png)

**Comment by q848899** [comment]
Hi 
 TW server Updated version the pugin is Not work   
please update thanks
