### ISSUE TITLE
DPS Meter not connecting to server?

### ISSUE THREAD

**Issue by Familiar235** [lunyx/CasualMeter#86]
Hello, i would like to know if its either my game, my country or maybe just my net is preventing Casual meter from connecting to the server? I Downloaded another Dmg meter but it's just plainly named "damage meter"
I have some Images to avoid confusion:
![screenshot_11](https://cloud.githubusercontent.com/assets/18483617/14561400/9a4fe782-0348-11e6-8779-2b7b425913c1.png)
![screenshot_12](https://cloud.githubusercontent.com/assets/18483617/14561399/9a1f018a-0348-11e6-8d17-a9f2d11fd892.png)
The second photo looks like its saying that there's some errors that it couldn't find something and involves WinPcap. I've downloaded it too btw.

**Comment by Gl0** [comment]
Seems there is no winpcap or winpcap capable network controllers.
Try to use raw sockets mode, don't forget to add firewall exception and run meter "as admin".

**Comment by Gl0** [comment]
Or try to use https://github.com/nmap/npcap/releases instead of winpcap

**Comment by Familiar235** [comment]
Thanks, ill try it out :3
