### ISSUE TITLE
Filter by group/name (enhancement)

### ISSUE THREAD

**Issue by Neofaucheur** [lunyx/CasualMeter#88]
Could you add an option to filter and record dps only for group members/white listed character ?
Because when fighting world boss the dps meter sometime record damage from player not fighting with you and not even the same boss. This can be pretty annoying when trying to see your dps on this kind of enemy.

I don't know if you have an (easy) way to figure out who's in your party but I hope so. Anyway a white list would be good enough for most scenario.

**Comment by Gl0** [comment]
We can add "solo mode" checkbox easily, "party mode" is more difficult, but doable. White list need more work with GUI and storage, party mode is simpler, and may be added to all opensource dpsmeters based on common Tera.Core at one time.

**Comment by Gl0** [comment]
Added party tracking functionality to Tera.Core, you can test how it works at ShinraMeter.
In Casual it will appear a bit later, now at the half of the way on adding abnormality tracking and data export, so party filter will come after them.

**Comment by Neofaucheur** [comment]
Nice, thanks for the answer and the added functionality.

**Comment by Gl0** [comment]
https://github.com/lunyx/CasualMeter/commit/96811a7b74795eeaf6e40eaf3c297dc11b3e93dc
