### ISSUE TITLE
Compact Mode

### ISSUE THREAD

**Issue by Blcksphr** [lunyx/CasualMeter#91]
Hello again!

This is not an issue just a thing I'm curious about.

When running in dungeons in raid DPS meter shows DPS in a compact mode, then I can't see my total crit rate.
Would it be possible to add an option to show Raid DPS as a normal mode and not in compact mode?

Thanks!

**Comment by Gl0** [comment]
Just edit config and increase number of users to show in full mode.

**Comment by Blcksphr** [comment]
Since I'm such noob, can you tell me how exactly to do that? :)

**Comment by Gl0** [comment]
Open %appdata%\CasualMeter\settings.json with notepad and change ExpandedViewPlayerLimit value.

**Comment by Blcksphr** [comment]
Damn, I thought that it might be that file, just got confused with that json thingy.

Well thx alot.
