### ISSUE TITLE
DPS Resets

### ISSUE THREAD

**Issue by Blcksphr** [lunyx/CasualMeter#92]
Hello again,

first let me tell you sorry for bothering you so much lately. Second awesome job you did with this Casual Meter.

Third I have found a bug that in Wonderholm when boss spawns totems with Colors the DPS on my meter usually resets. Is that only bug on my side or is it general bug?

Thanks for reply and keep up the good job!

**Comment by lunyx** [comment]
https://github.com/lunyx/CasualMeter/wiki/Settings-(Advanced)#inactivity-reset-duration

**Comment by Blcksphr** [comment]
Oh...yea I should probably read more carefuly next time..

 Big thx for help and sorry for bothering you, guys!
