### ISSUE TITLE
Unable to change Hotkeys

### ISSUE THREAD

**Issue by Brazuca87** [lunyx/CasualMeter#94]
I attempt to modify the settings file to have different modifier keys (Alt instead of Ctrl) and it doesn't do anything. A few minutes later, the program will automatically modify the values of the settings file.

Same seems to happen for other settings I change on the settings file (like InactivityResetDuration and ExpandedViewPlayerLimit)

**Comment by Gl0** [comment]
Do not edit config file while meter is running.

**Comment by Brazuca87** [comment]
Perfect, that solves it :)

Thanks :+1:
