### ISSUE TITLE
No DPS Stats - Windows 10

### ISSUE THREAD

**Issue by quantumstring** [lunyx/CasualMeter#96]
Provided that the meter is started before the TERA client it will show only the server to which the client is connected to. It will not show DPS statistics. Casual Meter log file indicates that it successfully enabled sniffing.

Supporting details:
- Windows 10 x64
- WinPCap 4.1.3
- CasualMeter-1.2.0.3-full.nupkg 9354191
- Not using VPN (raw sockets)
- Same behavior regardless of whether the executing user is an Administrator or not
- Local node host intrusion prevention system (HIPS) rule set updated to allow (ergo not a factor)

Related to #85

**Comment by Gl0** [comment]
1. Recent win10 update killed winpcap installation: if you are using it for a long time - it should be reinstalled.
2. Try using [npcap](https://github.com/nmap/npcap/releases)
3. Try raw sockets mode (this way require running as admin and inbound firewall exception rule. Recheck, that rule doesn't have any macros in the path like %localappdata%, or it would not work).

**Comment by Gl0** [comment]
If you are playing on TW server - you need to update [DB](https://github.com/neowutran/TeraDpsMeterData) manually or wait for the next release.

**Comment by lunyx** [comment]
Just released update.  Try restearting.

**Comment by Gl0** [comment]
Seems there is another problem at least with [NA MT server](https://github.com/neowutran/TeraDpsMeterData/commit/b713da5a4272030683e9fbc513bbb93370928755), need to recheck other servers ip addresses and release another update.

**Comment by lunyx** [comment]
Isn't that the same IP?

**Comment by Gl0** [comment]
.92 => .93

**Comment by lunyx** [comment]
I'm blind.

**Comment by lunyx** [comment]
Looks like there is a new bug with recording packets.  I'd hold off on updating right now.

**Comment by lunyx** [comment]
Fixed and released, along with MT backup server.

**Comment by quantumstring** [comment]
Confirmed working on Windows 10 x64 with npcap 0.07 r15 installed with WinPCap compatibility. Tested on HW server.

Thank you for the extremely rapid response!

**Comment by Gl0** [comment]
JP changed encryption - need update to latest Tea.Core.
